### ISSUE TITLE
Actividad 1 Preposiciones Simples y Compuestas

### ISSUE THREAD

**Issue by Fidel20-01** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Fidel20-01#1]
[24620171_1AS_ACT1.pdf](https://github.com/user-attachments/files/17372163/24620171_1AS_ACT1.pdf)

**Comment by Proyect-A16** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
